// Code generated by hertz generator.

package echo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _echoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _echomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
