// Code generated by Kitex v0.6.1. DO NOT EDIT.

package echosvc

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	echo "github.com/shawnnygoh/cloudwego-api-gateway/kitex_gen/echo"
)

func serviceInfo() *kitex.ServiceInfo {
	return echoSvcServiceInfo
}

var echoSvcServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "EchoSvc"
	handlerType := (*echo.EchoSvc)(nil)
	methods := map[string]kitex.MethodInfo{
		"EchoMethod": kitex.NewMethodInfo(echoMethodHandler, newEchoSvcEchoMethodArgs, newEchoSvcEchoMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "echo",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echo.EchoSvcEchoMethodArgs)
	realResult := result.(*echo.EchoSvcEchoMethodResult)
	success, err := handler.(echo.EchoSvc).EchoMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoSvcEchoMethodArgs() interface{} {
	return echo.NewEchoSvcEchoMethodArgs()
}

func newEchoSvcEchoMethodResult() interface{} {
	return echo.NewEchoSvcEchoMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoMethod(ctx context.Context, req *echo.EchoReq) (r *echo.EchoResp, err error) {
	var _args echo.EchoSvcEchoMethodArgs
	_args.Req = req
	var _result echo.EchoSvcEchoMethodResult
	if err = p.c.Call(ctx, "EchoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
